apiVersion: apps/v1
kind: Deployment
metadata:
  name: butterfly-classifier
  labels:
    app: butterfly-classifier
spec:
  replicas: 3
  selector:
    matchLabels:
      app: butterfly-classifier
  template:
    metadata:
      labels:
        app: butterfly-classifier
    spec:
      containers:
      - name: butterfly-classifier
        image: butterfly-classifier:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2005
        readinessProbe:
          httpGet:
            path: /
            port: 2005
          initialDelaySeconds: 5
          periodSeconds: 10