apiVersion: v1
kind: Service
metadata:
  name: butterfly-classifier-service
  labels:
    app: butterfly-classifier
    prometheus.io/scrape: "true"
    prometheus.io/port: "2005"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
    nginx.ingress.kubernetes.io/upstream-hash-by: "$request_id"
spec:
  selector:
    app: butterfly-classifier
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 0
  ports:
    - name: http-metrics
      protocol: TCP
      port: 80
      targetPort: 2005
  type: ClusterIP