apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: butterfly-classifier-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: butterfly-classifier-service
            port:
              number: 80